### ISSUE TITLE
modularize client

### ISSUE THREAD

**Issue by HagenMorano** [bitExpert/mattermost-client-node#10]
The current structure (`client.ts`) is hard to maintain. We should modularise the code. This is WIP, see [feature/modularize](https://github.com/bitExpert/mattermost-client-node/tree/feature/modularize)

**Comment by HagenMorano** [comment]
see PR: [https://github.com/bitExpert/mattermost-client-node/pull/12](https://github.com/bitExpert/mattermost-client-node/pull/12)

**Comment by DanielRuf** [comment]
Clsosing as this is alread done.
