### ISSUE TITLE
_apiCall => apiCall

### ISSUE THREAD

**Issue by DanielRuf** [bitExpert/mattermost-client-node#15]
It seems `_apiCall` was changed to `apiCall`. Is this planned and is this not internal anymore?
I think we should decide if and which methods should be declared as internal and use the underscore notation for this.

**Comment by HagenMorano** [comment]
It is now part of the Api class and must be public

**Comment by DanielRuf** [comment]
Ok, then let's remove the `@internal` tag or the complete DocBlock.
