### ISSUE TITLE
migrate away from request

### ISSUE THREAD

**Issue by DanielRuf** [bitExpert/mattermost-client-node#3]
https://github.com/request/request/issues/3143

Also needed for browser support.
See also https://github.com/sindresorhus/got#comparison for a comparison

**Comment by DanielRuf** [comment]
I think https://www.npmjs.com/package/node-fetch might be best (battle tested and actively maintained).

We would have to test this.

**Comment by HagenMorano** [comment]
https://github.com/sindresorhus/got#comparison

Going with `node-fetch` as it seems super awesome.
