### ISSUE TITLE
load all users from server

### ISSUE THREAD

**Issue by DanielRuf** [bitExpert/mattermost-client-node#9]
https://github.com/loafoe/mattermost-client/pull/112

cc @nr23730

**Comment by DanielRuf** [comment]
Hi @nr23730,

we have already improved the `loadUsers` method in our client.
The `byTeam` parameter is optional and defaults to `true`.

See https://github.com/bitExpert/mattermost-client-node/blob/4756bdc3c6835ccf14cf0766ba277c57014a8698/src/client.ts#L504-L512

So I think we can close this as this should be already supported.

**Comment by DanielRuf** [comment]
@nr23730 can we close this as resolved?

**Comment by nr23730** [comment]
The code looks good but I haven't tried it yet.

**Comment by nr23730** [comment]
Works like a charm! Thank you!
